version: '3.2'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:3000
    container_name: django_web
#    volumes:
#      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web