version: '3.2'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"

  redis:
    hostname: redis
    image: redis:alpine
    expose:
      - "6379"

  db:
    image: postgres
  web:
    build: .
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - GOOGLEMAPS_APIKEY=${GOOGLEMAPS_APIKEY}
    command: /bin/bash startserver.sh
    container_name: django_web
    ports:
      - "3000:3000"
    depends_on:
      - db
  worker:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - RABBITMQ_USER=${RABBITMQ_USER}
        - RABBITMQ_PASS=${RABBITMQ_PASS}
      links:
          - rabbit
      depends_on:
          - rabbit
          - redis
      entrypoint: celery -A taskqueue worker --app=taskqueue.celery_app:app --loglevel=info

  nginx:
    build:
      context: ./nginx
      args:
        - HTPASSWD=${HTPASSWD}
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web

  flower:
    hostname: flower
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    depends_on:
      - rabbit
    entrypoint: celery flower -A taskqueue --url_prefix=flower --app=taskqueue.celery_app:app --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbit:5672// --port=5000
    ports:
      - "5000:5000"