version: '3.2'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=kanin
    ports:
      - "5672:5672"

  redis:
    hostname: redis
    image: redis:alpine
    expose:
      - "6379"

  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:3000
    container_name: django_web
    ports:
      - "3000:3000"
    depends_on:
      - db
  worker:
      build:
        context: .
        dockerfile: Dockerfile
      links:
          - rabbit
      depends_on:
          - rabbit
          - redis
      entrypoint: celery -A taskqueue worker --app=taskqueue.celery_app:app --loglevel=info

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web

  flower:
    hostname: flower
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    entrypoint: celery flower -A taskqueue --app=taskqueue.celery_app:app --broker=amqp://admin:kanin@rabbit:5672// --port=5000
    ports:
      - "5000:5000"