# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datatype', models.CharField(choices=[('L', 'Location CSV'), ('A', 'Accelerometer CSV')], max_length=1)),
                ('data', models.BinaryField(help_text='The file contents')),
                ('name', models.CharField(help_text='File name', max_length=256)),
                ('size', models.BigIntegerField(default=-1, help_text='The size of the file, derived from the data field and stored for speed')),
            ],
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
                ('source', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='collector.File')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(help_text='User owning this file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
