# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToJsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.File')),
            ],
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='filetojsondata',
            name='jsondata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.JsonData'),
        ),
    ]
