# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_file_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='datatype',
        ),
    ]
