# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_remove_file_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='source',
            field=models.ForeignKey(default=1, help_text='File this track was extracted from', on_delete=django.db.models.deletion.CASCADE, to='collector.File'),
            preserve_default=False,
        ),
    ]
