# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20171104_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
    ]
