# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20171103_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetojsondata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filetojsondata',
            name='jsondata',
        ),
        migrations.AddField(
            model_name='file',
            name='jsondata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.JsonData'),
        ),
        migrations.DeleteModel(
            name='FileToJsonData',
        ),
    ]
